### ISSUE TITLE
A note on precedent

### ISSUE THREAD

**Issue by jwarkentin** [isiahmeadows/proposal-try-expression#2]
I'm not sure if this is a serious proposal that might be going somewhere but I've wanted it for years. I didn't see it mentioned in the part about previous language precedent but Kotlin has had try expressions for a long time. See here: https://kotlinlang.org/docs/exceptions.html#try-is-an-expression

I don't know if there is anything worthwhile from a proposal or implementation perspective that can be gleaned from that but Kotlin syntax generally feels quite similar to JS and can transpile to JS so I thought I'd bring it up in case it hasn't already been reviewed or considered.

**Comment by dead-claudia** [comment]
I'm aware of Kotlin's `try`/`catch` expression. This is more directly inspired by [Lua's `pcall`](https://www.lua.org/manual/5.4/manual.html#pdf-pcall), though, if you look at that. Rust's [`std::panic::catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) is similar, though it's not used as broadly because its `Result<T, E>` type is idiomatically preferred (complete with built-in syntax to make it easier to use).
